open Recognizer
let%test ""  = belongsTo ['0';'0'] = [true;false;true;false;true]
let%test ""  = belongsTo ['0';'1';'1'] = [true;true;false;true;false]
let%test "" = belongsTo ['0'] = [true; true; false; false; false]
let%test "" = belongsTo ['1'] = [true; true; false; false; false]
let%test "" = belongsTo ['0'; '1'; '0'] = [true; false; true; false; false]
let%test "" = belongsTo ['0'] = [true; true; false; false; false]
let%test "" = belongsTo ['1'] = [true; true; false; false; false]
let%test "" = belongsTo ['0'; '1'] = [true; true; false; false; false]
let%test "" = belongsTo ['1'; '1'; '1'] = [true; true; false; false; false]
let%test "" = belongsTo ['1'; '1'] = [true; true; false; true; true]
let%test "" = belongsTo ['0'; '1'; '0'; '1'] = [true; false; false; true; false]
let%test "" = belongsTo ['0'; '0'] = [true; false; true; false; true]
let%test "" = belongsTo ['1'; '1'] = [true; true; false; true; true]
let%test "" = belongsTo ['0'; '0'; '1'; '1'] = [true; false; false; true; true]
